var hierarchy =
[
    [ "astarte::device::Data", "classastarte_1_1device_1_1Data.html", null ],
    [ "astarte::device::DatastreamIndividual", "classastarte_1_1device_1_1DatastreamIndividual.html", null ],
    [ "astarte::device::DatastreamObject", "classastarte_1_1device_1_1DatastreamObject.html", null ],
    [ "astarte::device::Device", "classastarte_1_1device_1_1Device.html", [
      [ "astarte::device::grpc::DeviceGrpc", "classastarte_1_1device_1_1grpc_1_1DeviceGrpc.html", null ],
      [ "astarte::device::mqtt::DeviceMqtt", "classastarte_1_1device_1_1mqtt_1_1DeviceMqtt.html", null ]
    ] ],
    [ "astarte::device::ErrorBase", "classastarte_1_1device_1_1ErrorBase.html", [
      [ "astarte::device::DataSerializationError", "classastarte_1_1device_1_1DataSerializationError.html", null ],
      [ "astarte::device::FileOpenError", "classastarte_1_1device_1_1FileOpenError.html", null ],
      [ "astarte::device::GrpcLibError", "classastarte_1_1device_1_1GrpcLibError.html", null ],
      [ "astarte::device::InterfaceValidationError", "classastarte_1_1device_1_1InterfaceValidationError.html", null ],
      [ "astarte::device::InternalError", "classastarte_1_1device_1_1InternalError.html", null ],
      [ "astarte::device::InvalidAstarteTypeError", "classastarte_1_1device_1_1InvalidAstarteTypeError.html", null ],
      [ "astarte::device::InvalidDatabaseRetentionPolicyError", "classastarte_1_1device_1_1InvalidDatabaseRetentionPolicyError.html", null ],
      [ "astarte::device::InvalidInputError", "classastarte_1_1device_1_1InvalidInputError.html", null ],
      [ "astarte::device::InvalidInterfaceAggregationError", "classastarte_1_1device_1_1InvalidInterfaceAggregationError.html", null ],
      [ "astarte::device::InvalidInterfaceOwnershipeError", "classastarte_1_1device_1_1InvalidInterfaceOwnershipeError.html", null ],
      [ "astarte::device::InvalidInterfaceTypeError", "classastarte_1_1device_1_1InvalidInterfaceTypeError.html", null ],
      [ "astarte::device::InvalidInterfaceVersionError", "classastarte_1_1device_1_1InvalidInterfaceVersionError.html", null ],
      [ "astarte::device::InvalidReliabilityError", "classastarte_1_1device_1_1InvalidReliabilityError.html", null ],
      [ "astarte::device::InvalidRetentionError", "classastarte_1_1device_1_1InvalidRetentionError.html", null ],
      [ "astarte::device::MsgHubError", "classastarte_1_1device_1_1MsgHubError.html", null ],
      [ "astarte::device::OperationRefusedError", "classastarte_1_1device_1_1OperationRefusedError.html", null ],
      [ "astarte::device::mqtt::CryptoError", "classastarte_1_1device_1_1mqtt_1_1CryptoError.html", null ],
      [ "astarte::device::mqtt::DeviceRegistrationError", "classastarte_1_1device_1_1mqtt_1_1DeviceRegistrationError.html", null ],
      [ "astarte::device::mqtt::HttpError", "classastarte_1_1device_1_1mqtt_1_1HttpError.html", null ],
      [ "astarte::device::mqtt::InvalidUrlError", "classastarte_1_1device_1_1mqtt_1_1InvalidUrlError.html", null ],
      [ "astarte::device::mqtt::JsonParsingError", "classastarte_1_1device_1_1mqtt_1_1JsonParsingError.html", null ],
      [ "astarte::device::mqtt::MqttConnectionError", "classastarte_1_1device_1_1mqtt_1_1MqttConnectionError.html", null ],
      [ "astarte::device::mqtt::MqttError", "classastarte_1_1device_1_1mqtt_1_1MqttError.html", null ],
      [ "astarte::device::mqtt::PairingApiError", "classastarte_1_1device_1_1mqtt_1_1PairingApiError.html", null ],
      [ "astarte::device::mqtt::PairingConfigError", "classastarte_1_1device_1_1mqtt_1_1PairingConfigError.html", null ],
      [ "astarte::device::mqtt::ReadCredentialError", "classastarte_1_1device_1_1mqtt_1_1ReadCredentialError.html", null ],
      [ "astarte::device::mqtt::RetrieveBrokerUrlError", "classastarte_1_1device_1_1mqtt_1_1RetrieveBrokerUrlError.html", null ],
      [ "astarte::device::mqtt::UuidError", "classastarte_1_1device_1_1mqtt_1_1UuidError.html", null ],
      [ "astarte::device::mqtt::WriteCredentialError", "classastarte_1_1device_1_1mqtt_1_1WriteCredentialError.html", null ]
    ] ],
    [ "astarte::device::Message", "classastarte_1_1device_1_1Message.html", null ],
    [ "astarte::device::mqtt::Config", "classastarte_1_1device_1_1mqtt_1_1Config.html", null ],
    [ "astarte::device::mqtt::PairingApi", "classastarte_1_1device_1_1mqtt_1_1PairingApi.html", null ],
    [ "astarte::device::PropertyIndividual", "classastarte_1_1device_1_1PropertyIndividual.html", null ],
    [ "astarte::device::StoredProperty", "classastarte_1_1device_1_1StoredProperty.html", null ],
    [ "astarte_fmt::formatter< T >", "structastarte__fmt_1_1formatter.html", null ],
    [ "astarte_fmt::formatter< astarte::device::Data >", "structastarte__fmt_1_1formatter_3_01astarte_1_1device_1_1Data_01_4.html", null ],
    [ "astarte_fmt::formatter< astarte::device::DatastreamIndividual >", "structastarte__fmt_1_1formatter_3_01astarte_1_1device_1_1DatastreamIndividual_01_4.html", null ],
    [ "astarte_fmt::formatter< astarte::device::DatastreamObject >", "structastarte__fmt_1_1formatter_3_01astarte_1_1device_1_1DatastreamObject_01_4.html", null ],
    [ "astarte_fmt::formatter< astarte::device::Error >", "structastarte__fmt_1_1formatter_3_01astarte_1_1device_1_1Error_01_4.html", null ],
    [ "astarte_fmt::formatter< astarte::device::ErrorBase >", "structastarte__fmt_1_1formatter_3_01astarte_1_1device_1_1ErrorBase_01_4.html", null ],
    [ "astarte_fmt::formatter< astarte::device::Message >", "structastarte__fmt_1_1formatter_3_01astarte_1_1device_1_1Message_01_4.html", null ],
    [ "astarte_fmt::formatter< astarte::device::Ownership >", "structastarte__fmt_1_1formatter_3_01astarte_1_1device_1_1Ownership_01_4.html", null ],
    [ "astarte_fmt::formatter< astarte::device::PropertyIndividual >", "structastarte__fmt_1_1formatter_3_01astarte_1_1device_1_1PropertyIndividual_01_4.html", null ],
    [ "astarte_fmt::formatter< astarte::device::StoredProperty >", "structastarte__fmt_1_1formatter_3_01astarte_1_1device_1_1StoredProperty_01_4.html", null ],
    [ "astarte_fmt::formatter< astarte::device::Type >", "structastarte__fmt_1_1formatter_3_01astarte_1_1device_1_1Type_01_4.html", null ]
];