var namespace_astarte_device_s_d_k_c_sharp_1_1_protocol =
[
    [ "AstarteEvents", "namespace_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_events.html", "namespace_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_events" ],
    [ "AstarteException", "namespace_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_exception.html", "namespace_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_exception" ],
    [ "AstarteAggregateDatastreamInterface", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_aggregate_datastream_interface.html", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_aggregate_datastream_interface" ],
    [ "AstarteDatastreamInterface", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_datastream_interface.html", null ],
    [ "AstarteDeviceAggregateDatastreamInterface", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_device_aggregate_datastream_interface.html", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_device_aggregate_datastream_interface" ],
    [ "AstarteDeviceDatastreamInterface", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_device_datastream_interface.html", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_device_datastream_interface" ],
    [ "AstarteDevicePropertyInterface", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_device_property_interface.html", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_device_property_interface" ],
    [ "AstarteGlobalEventListener", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_global_event_listener.html", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_global_event_listener" ],
    [ "IAstartePropertyEventListener", "interface_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_i_astarte_property_event_listener.html", "interface_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_i_astarte_property_event_listener" ],
    [ "AstarteInterfaceDatastreamMapping", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_interface_datastream_mapping.html", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_interface_datastream_mapping" ],
    [ "AstartePropertyInterface", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_property_interface.html", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_property_interface" ],
    [ "AstarteServerAggregateDatastreamInterface", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_server_aggregate_datastream_interface.html", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_server_aggregate_datastream_interface" ],
    [ "AstarteServerDatastreamInterface", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_server_datastream_interface.html", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_server_datastream_interface" ],
    [ "AstarteServerPropertyInterface", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_server_property_interface.html", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_server_property_interface" ],
    [ "IAstarteAggregateDataStreamer", "interface_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_i_astarte_aggregate_data_streamer.html", "interface_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_i_astarte_aggregate_data_streamer" ],
    [ "IAstarteDataStreamer", "interface_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_i_astarte_data_streamer.html", "interface_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_i_astarte_data_streamer" ],
    [ "IAstartePropertySetter", "interface_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_i_astarte_property_setter.html", "interface_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_i_astarte_property_setter" ]
];