var class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_exception_1_1_astarte_invalid_interface_exception =
[
    [ "AstarteInvalidInterfaceException", "class_astarte_device_s_d_k_c_sharp_1_1_protocol_1_1_astarte_exception_1_1_astarte_invalid_interface_exception.html#a3da92b30e199c3c21dc98a02ed2f5c31", null ]
];